name: IP Generator

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          python script.py

      - name: Commit changes to private repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ips.txt README.md
          git commit -m "Update files" || echo "No changes to commit"
          git push origin main

      - name: Sync output files to public repo
        run: |
          git config --global user.email "171773043+darknessm427@users.noreply.github.com"
          git config --global user.name "darknessm427"

          git clone https://x-access-token:${{ secrets.PUSH_TOKEN_PUBLIC }}@github.com/darknessm427/IP_Generator.git public-repo
          cp ips.txt README.md public-repo/

          cd public-repo
          git add ips.txt README.md
          git commit -m "SYNCED $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
